import type { ContentMutation, Project, SiteSettings } from "@layered/contracts";

export const defaultSettings: SiteSettings = {
  title: "LAYERED.work",
  versionLabel: "v2.0",
  navigation: [
    { key: "home", label: "~/home", href: "#home" },
    { key: "projects", label: "./projects", href: "#projects" },
    { key: "blog", label: "./blog", href: "#blog" },
    { key: "about", label: "./about", href: "#about" },
  ],
  home: {
    heroPrompt: "whoami --verbose",
    heroNameA: "Frank",
    heroNameB: "Gregor",
    heroLineMutedA: "Building",
    heroLineGold: "things",
    heroLineMutedB: "that",
    heroLineBurnt: "layer",
    intro:
      "30 Jahre Softwareentwicklung. Heute stecke ich meine Zeit in 3D-Druck, 3D-Design, etwas Elektronik und sehr viel LLM-Experimente.",
    featuredPostSlug: "next-mini-replica",
    pressHint: "press anywhere to navigate",
  },
  about: {
    prompt: "cat ~/about.md",
    paragraphs: [
      "I'm Frank Gregor. I wrote software for a living for thirty years. Commercial, open source, embedded, desktop, mobile, server. At some point I stopped counting languages.",
      "These days my time goes into 3D printing, 3D design, a small amount of electronics, and an absurd amount of LLM experimentation. This site is where I document the parts that survive.",
      "I live in Bregenz, Austria, at the eastern end of Lake Constance. The mountains are loud, the lake is quiet, and both are good for thinking.",
    ],
    stack: [
      { label: "Design", value: "Fusion360" },
      { label: "Print", value: "Bambu P1S" },
      { label: "Code", value: "Swift · Rust · TS" },
      { label: "Edit", value: "Neovim · Xcode" },
      { label: "LLM", value: "Claude · local" },
    ],
    socials: [
      { label: "Mastodon", href: "https://mastodon.social/@phranck", icon: "mastodon" },
      { label: "GitHub", href: "https://github.com/phranck", icon: "github" },
      { label: "YouTube", href: "https://youtube.com/@phranck", icon: "youtube" },
      { label: "Instagram", href: "https://instagram.com/phranck", icon: "instagram" },
      { label: "XING", href: "https://xing.com/profile/frank_gregor", icon: "xing" },
    ],
  },
  footer: {
    eofLabel: "EOF",
    locationText: "made with ❤ in Bregenz / Lake Constance / AT",
    copyright: "© 2026 Frank Gregor · v2.0 · Mockup 1 — Techy Minimal",
  },
  blog: {
    pageSize: 6,
    gridPreviewLength: 140,
    listPreviewLength: 280,
  },
  projects: {
    gridPreviewLength: 120,
    listPreviewLength: 240,
    visibleFilterCount: 6,
  },
  design: {
    colors: {
      bg: "#171715",
      bgElev: "#262623",
      border: "#3a3a36",
      text: "#efefec",
      muted: "#90908a",
      accent: "#00d9ff",
      accentDim: "#0099b3",
      stripeTeal: "#2b7488",
      stripeOlive: "#758c34",
      stripeGold: "#fbac3e",
      stripeBurnt: "#c64616",
    },
    typography: {
      bodyFamily: "Barlow",
      monoFamily: "JetBrains Mono",
      headingWeight: 800,
      bodyWeight: 400,
    },
    radius: {
      card: 20,
      image: 16,
      control: 12,
    },
    terminal: {
      promptColor: "#00d9ff",
      cursorColor: "#00d9ff",
      showCursor: true,
    },
  },
};

export const seedProjects: Array<ContentMutation & { id: string }> = [
  {
    id: "project_next_soundbox",
    slug: "next-soundbox",
    title: "NeXT SoundBox",
    description:
      "Wireless speaker in the aesthetic of the NeXTcube. 3D-printed enclosure, bluetooth audio board, custom power path.",
    previewText: "Wireless speaker in NeXTcube aesthetic.",
    imageUrl: "https://layered.work/media/posts/7/schematic.png",
    imageAlt: "NeXT SoundBox",
    tags: ["Hardware", "3DPrint", "NeXT"],
    categories: ["Hardware", "Electronics", "3D"],
    status: "published",
    date: "2025-12-11T00:00:00.000Z",
    publishedAt: "2025-12-11T00:00:00.000Z",
    markdown:
      "## Why\n\nI wanted a speaker that earned its spot on my desk. Nothing on the market looked like it had been designed by someone who had ever touched a NeXT machine. So I drew one.\n\n## Build log\n\n- Fusion360 parametric model\n- Bambu P1S with matte black PLA\n- Sure Electronics 2x25W amp board\n- Custom fabric grille from 1970s hi-fi stock\n\n## Firmware\n\n```swift\n// BLE pairing helper\nfunc startPairing() {\n  audioManager.reset()\n  peripheral.discoverServices(nil)\n}\n```\n\nPlaceholder content. Real detail page will pull from Markdown with embedded assets and galleries.",
    terminalPrompt: "cat ~/projects/next-soundbox.md",
    model: { src: "next-soundbox.glb" },
  },
  {
    id: "project_gimli",
    slug: "gimli",
    title: "Gimli",
    description: "A small utility for Mac developers. Fast, keyboard-driven, no-nonsense.",
    previewText: "Bamboo speaker — warm sound, warmer material.",
    imageUrl: "https://layered.work/media/posts/16/img_0528-2.webp",
    imageAlt: "Gimli",
    tags: ["Software", "Mac"],
    categories: ["Hardware", "3D"],
    status: "published",
    date: "2025-11-25T00:00:00.000Z",
    publishedAt: "2025-11-25T00:00:00.000Z",
    markdown: "## Notes\n\nA small utility for Mac developers. Fast, keyboard-driven, no-nonsense.",
  },
  {
    id: "project_touch_magic",
    slug: "touch-magic",
    title: "Touch Magic",
    description: "Makes the MacBook Touch Bar useful again. Native SwiftUI, customizable layouts.",
    previewText: "Makes the MacBook Touch Bar useful again.",
    imageUrl: "https://layered.work/media/posts/20/banner-touch-magic.jpeg",
    imageAlt: "Touch Magic",
    tags: ["Software", "SwiftUI"],
    categories: ["Software"],
    status: "published",
    date: "2025-10-12T00:00:00.000Z",
    publishedAt: "2025-10-12T00:00:00.000Z",
    markdown: "## Notes\n\nMakes the MacBook Touch Bar useful again.",
  },
  {
    id: "project_pandadock",
    slug: "pandadock",
    title: "PandaDock",
    description: "A dock replacement with spatial memory and workspace awareness.",
    previewText: "Dock replacement with spatial memory.",
    imageUrl: "https://layered.work/media/posts/18/banner-pandadock.jpeg",
    imageAlt: "PandaDock",
    tags: ["Software", "Mac"],
    categories: ["Software"],
    status: "published",
    date: "2025-09-18T00:00:00.000Z",
    publishedAt: "2025-09-18T00:00:00.000Z",
    markdown: "## Notes\n\nA dock replacement with spatial memory and workspace awareness.",
  },
  {
    id: "project_next_mini_replica",
    slug: "next-mini-replica",
    title: "NeXT mini Replica",
    description: "3D-printed miniature NeXTcube with RPi 5 inside.",
    previewText: "3D-printed miniature NeXTcube with RPi5.",
    imageUrl: "https://layered.work/media/posts/17/NeXTcube-mini.jpg",
    imageAlt: "NeXT mini Replica",
    tags: ["Hardware", "3DPrint", "NeXT"],
    categories: ["Hardware", "3D", "Electronics"],
    status: "published",
    date: "2025-12-11T00:00:00.000Z",
    publishedAt: "2025-12-11T00:00:00.000Z",
    markdown:
      "## Interest\n\nThis project is a labor of love that I've been working on for a very long time. Not continuously, but every now and then when the pieces finally click into place.",
  },
];

export const seedPosts: Array<ContentMutation & { id: string }> = [
  {
    id: "post_next_mini_replica",
    slug: "next-mini-replica",
    title: "NeXT mini Replica Interest",
    description:
      "This project is a labor of love that I've been working on for a very long time. Not continuously, but every now and then when the pieces finally click into place.",
    previewText: "Long-term labor of love.",
    imageUrl: "https://layered.work/media/posts/17/NeXTcube-mini.jpg",
    imageAlt: "NeXT mini Replica",
    tags: ["3DPrint", "NeXT", "Hardware"],
    status: "published",
    date: "2025-12-11T00:00:00.000Z",
    publishedAt: "2025-12-11T00:00:00.000Z",
    readTimeMinutes: 6,
    markdown:
      "This project is a labor of love that I've been working on for a very long time. Not continuously, but every now and then when the pieces finally click into place.",
  },
  {
    id: "post_nextstep_naming",
    slug: "nextstep-naming",
    title: "NeXTSTEP Naming",
    description: "Why every Apple OS still carries the capital letters of a dead company.",
    previewText: "Why every Apple OS still carries the capital letters of a dead company.",
    imageUrl: "https://layered.work/media/posts/32/banner_NeXT_naming.jpg",
    imageAlt: "NeXTSTEP Naming",
    tags: ["OS", "NeXTSTEP"],
    status: "published",
    date: "2025-12-07T00:00:00.000Z",
    publishedAt: "2025-12-07T00:00:00.000Z",
    readTimeMinutes: 4,
    markdown: "Why every Apple OS still carries the capital letters of a dead company.",
  },
  {
    id: "post_ai_operating_guide",
    slug: "ai-operating-guide",
    title: "AI Operating Guide",
    description: "Strategies for consistent, high-quality output from LLMs.",
    previewText: "Strategies for consistent, high-quality output from LLMs.",
    imageUrl: "https://layered.work/media/posts/30/banner-ai-operation-guide.jpg",
    imageAlt: "AI Operating Guide",
    tags: ["LLM", "AI", "Workflow"],
    status: "published",
    date: "2025-12-01T00:00:00.000Z",
    publishedAt: "2025-12-01T00:00:00.000Z",
    readTimeMinutes: 9,
    markdown:
      "Every week I watch someone describe the same AI workflow problem in a different disguise. The model forgets. The model hallucinates. The model confidently rewrites code that was fine.\n\nMost of these aren't model problems. They're operating problems — how you set up the conversation, how you hand over context, how you hand off between sessions.\n\n## Context is a resource, not an ambient gas\n\nTreat the context window like you treat RAM on an embedded device. Every token you burn on filler is a token that isn't available for reasoning. Write dense. Cut pleasantries.\n\n```plaintext\n// before\n\"Could you please help me understand...\"\n\n// after\n\"explain:\"\n```\n\n## Persistence belongs on disk\n\nThe conversation is ephemeral. If a fact matters for tomorrow, it goes in a file — `CLAUDE.md`, `AGENTS.md`, a memory note. If a decision matters for the next PR, it goes in the spec.\n\n## Clarity comes from constraints\n\nGive the model a role, a goal, a set of things it may not touch, and a definition of done. Vague prompts produce vague output. This is not a model limitation. It's physics.",
  },
  {
    id: "post_editor_cheat_sheets",
    slug: "editor-cheat-sheets",
    title: "Editor Cheat-Sheets for Mac Keyboards",
    description: "Printable cards for editors I keep forgetting shortcuts for.",
    previewText: "Printable cards for editors I keep forgetting shortcuts for.",
    imageUrl: "https://layered.work/media/posts/26/banner-texteditors.jpg",
    imageAlt: "Editor Cheat-Sheets",
    tags: ["Editor", "Mac"],
    status: "published",
    date: "2025-08-31T00:00:00.000Z",
    publishedAt: "2025-08-31T00:00:00.000Z",
    readTimeMinutes: 3,
    markdown: "Printable cards for editors I keep forgetting shortcuts for.",
  },
  {
    id: "post_rpi5_leds",
    slug: "rpi5-leds",
    title: "External Activity and Power LEDs on RPi 5",
    description: "Routing onboard LEDs to panel-mount ones without going mad.",
    previewText: "Routing onboard LEDs to panel-mount ones without going mad.",
    imageUrl: "https://layered.work/media/posts/25/banner-rpi5-external-leds-2.jpg",
    imageAlt: "RPi 5 LEDs",
    tags: ["Electronics", "RaspberryPi"],
    status: "published",
    date: "2025-08-30T00:00:00.000Z",
    publishedAt: "2025-08-30T00:00:00.000Z",
    readTimeMinutes: 5,
    markdown: "Routing onboard LEDs to panel-mount ones without going mad.",
  },
  {
    id: "post_nextstep_rpi5",
    slug: "nextstep-rpi5",
    title: "NeXTSTEP: On a RPi 5",
    description: "Yes it runs. No it's not useful. Yes it's wonderful.",
    previewText: "Yes it runs. No it's not useful. Yes it's wonderful.",
    imageUrl: "https://layered.work/media/posts/24/banner-nextstep33-2.jpg",
    imageAlt: "NeXTSTEP on RPi 5",
    tags: ["NeXTSTEP", "RaspberryPi"],
    status: "published",
    date: "2025-08-22T00:00:00.000Z",
    publishedAt: "2025-08-22T00:00:00.000Z",
    readTimeMinutes: 12,
    markdown: "Yes it runs. No it's not useful. Yes it's wonderful.",
  },
  {
    id: "post_website_design_2",
    slug: "website-design-2",
    title: "Website Design: Die Zweite",
    description: "Ein Rant ueber meine eigene Seite und warum sie nicht bleiben darf.",
    previewText: "Ein Rant ueber meine eigene Seite und warum sie nicht bleiben darf.",
    imageUrl: "https://layered.work/media/posts/22/banner-website-design.jpg",
    imageAlt: "Website Design: Die Zweite",
    tags: ["Web", "Design"],
    status: "published",
    date: "2025-08-08T00:00:00.000Z",
    publishedAt: "2025-08-08T00:00:00.000Z",
    readTimeMinutes: 4,
    markdown: "Ein Rant ueber meine eigene Seite und warum sie nicht bleiben darf.",
  },
  {
    id: "post_swift_nested_ternary",
    slug: "swift-nested-ternary",
    title: "Swift: Don't use nested ternary operators",
    description: "One small opinion I will die on.",
    previewText: "One small opinion I will die on.",
    imageUrl: "https://layered.work/media/posts/14/Hero-Swift-2xl-2.jpg",
    imageAlt: "Swift ternary",
    tags: ["Swift"],
    status: "published",
    date: "2023-06-12T00:00:00.000Z",
    publishedAt: "2023-06-12T00:00:00.000Z",
    readTimeMinutes: 2,
    markdown: "One small opinion I will die on.",
  },
  {
    id: "post_mastodon_love",
    slug: "mastodon-love",
    title: "Mastodon: A new Love",
    description: "Leaving the bird site for something slower and weirder.",
    previewText: "Leaving the bird site for something slower and weirder.",
    imageUrl: "https://layered.work/media/posts/19/banner-mastodon.jpg",
    imageAlt: "Mastodon",
    tags: ["Fediverse", "Mastodon"],
    status: "published",
    date: "2022-06-05T00:00:00.000Z",
    publishedAt: "2022-06-05T00:00:00.000Z",
    readTimeMinutes: 3,
    markdown: "Leaving the bird site for something slower and weirder.",
  },
];

export function projectToPublicShape(project: ContentMutation & { id: string }): Project {
  return {
    id: project.id,
    slug: project.slug,
    title: project.title,
    description: project.description,
    previewText: project.previewText ?? null,
    imageUrl: project.imageUrl ?? null,
    imageAlt: project.imageAlt ?? null,
    tags: project.tags,
    categories: project.categories ?? [],
    status: project.status,
    publishedAt: project.publishedAt ?? null,
    markdown: project.markdown,
    terminalPrompt: project.terminalPrompt ?? null,
    model: project.model ?? null,
  };
}
