import type { IconProps } from "@phosphor-icons/react";
import {
  AddressBookIcon,
  AirplaneIcon,
  AlarmIcon,
  ArchiveBoxIcon,
  ArmchairIcon,
  ArrowBendDownLeftIcon,
  ArrowBendDownRightIcon,
  ArrowBendUpLeftIcon,
  ArrowBendUpRightIcon,
  ArrowCircleDownIcon,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  ArrowCircleUpIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowElbowDownLeftIcon,
  ArrowElbowDownRightIcon,
  ArrowElbowLeftIcon,
  ArrowElbowRightIcon,
  ArrowElbowUpLeftIcon,
  ArrowElbowUpRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  BagIcon,
  BalloonIcon,
  BankIcon,
  BatteryChargingIcon,
  BellIcon,
  BicycleIcon,
  BinocularsIcon,
  BookIcon,
  BookmarkIcon,
  BooksIcon,
  BriefcaseIcon,
  BrowserIcon,
  BuildingsIcon,
  CalendarIcon,
  CameraIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CarIcon,
  CertificateIcon,
  ChartBarIcon,
  ChartLineUpIcon,
  ChartPieSliceIcon,
  ChatCircleIcon,
  ChatCircleTextIcon,
  ClipboardTextIcon,
  ClockIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudIcon,
  CompassIcon,
  CreditCardIcon,
  CrownIcon,
  CurrencyCircleDollarIcon,
  DesktopIcon,
  DeviceMobileIcon,
  DiceFiveIcon,
  DoorOpenIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EyeIcon,
  FactoryIcon,
  FileIcon,
  FireIcon,
  FlagIcon,
  FlowerIcon,
  FolderIcon,
  GameControllerIcon,
  GearIcon,
  GiftIcon,
  GitBranchIcon,
  GlobeHemisphereWestIcon,
  GlobeIcon,
  HandCoinsIcon,
  HandPalmIcon,
  HandWavingIcon,
  HardDrivesIcon,
  HeadphonesIcon,
  HeartIcon,
  HouseIcon,
  IdentificationCardIcon,
  ImageIcon,
  KeyIcon,
  LampIcon,
  LaptopIcon,
  LifebuoyIcon,
  LightningIcon,
  ListBulletsIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapTrifoldIcon,
  MedalIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MoonIcon,
  MusicNotesIcon,
  NewspaperIcon,
  PackageIcon,
  PaletteIcon,
  PaperclipIcon,
  PaperPlaneTiltIcon,
  PauseIcon,
  PencilSimpleIcon,
  PhoneIcon,
  PlayIcon,
  ReceiptIcon,
  RepeatIcon,
  RocketLaunchIcon,
  RssIcon,
  ScalesIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  ShuffleIcon,
  SmileyIcon,
  SparkleIcon,
  StarIcon,
  SuitcaseIcon,
  SunIcon,
  TagIcon,
  TelevisionIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TicketIcon,
  TrainIcon,
  TrayIcon,
  UserCircleIcon,
  UserIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  WaveformIcon,
} from "@phosphor-icons/react";
import { type ComponentType, createElement } from "react";

export type ButtonIconComponent = ComponentType<IconProps>;

function withDuotone(Icon: ButtonIconComponent): ButtonIconComponent {
  function DuotoneButtonIcon(props: IconProps) {
    return createElement(Icon, { weight: "duotone", ...props });
  }

  DuotoneButtonIcon.displayName = `Duotone${Icon.displayName ?? Icon.name ?? "ButtonIcon"}`;
  return DuotoneButtonIcon;
}

export const BUTTON_ICON_COMPONENTS = {
  "address-book": withDuotone(AddressBookIcon),
  airplane: withDuotone(AirplaneIcon),
  alarm: withDuotone(AlarmIcon),
  "archive-box": withDuotone(ArchiveBoxIcon),
  armchair: withDuotone(ArmchairIcon),
  "arrow-bend-down-left": withDuotone(ArrowBendDownLeftIcon),
  "arrow-bend-down-right": withDuotone(ArrowBendDownRightIcon),
  "arrow-bend-up-left": withDuotone(ArrowBendUpLeftIcon),
  "arrow-bend-up-right": withDuotone(ArrowBendUpRightIcon),
  "arrow-circle-down": withDuotone(ArrowCircleDownIcon),
  "arrow-circle-left": withDuotone(ArrowCircleLeftIcon),
  "arrow-circle-right": withDuotone(ArrowCircleRightIcon),
  "arrow-circle-up": withDuotone(ArrowCircleUpIcon),
  "arrow-clockwise": withDuotone(ArrowClockwiseIcon),
  "arrow-counter-clockwise": withDuotone(ArrowCounterClockwiseIcon),
  "arrow-down": withDuotone(ArrowDownIcon),
  "arrow-elbow-down-left": withDuotone(ArrowElbowDownLeftIcon),
  "arrow-elbow-down-right": withDuotone(ArrowElbowDownRightIcon),
  "arrow-elbow-left": withDuotone(ArrowElbowLeftIcon),
  "arrow-elbow-right": withDuotone(ArrowElbowRightIcon),
  "arrow-elbow-up-left": withDuotone(ArrowElbowUpLeftIcon),
  "arrow-elbow-up-right": withDuotone(ArrowElbowUpRightIcon),
  "arrow-left": withDuotone(ArrowLeftIcon),
  "arrow-right": withDuotone(ArrowRightIcon),
  "arrow-square-out": withDuotone(ArrowSquareOutIcon),
  "arrow-up": withDuotone(ArrowUpIcon),
  bag: withDuotone(BagIcon),
  balloon: withDuotone(BalloonIcon),
  bank: withDuotone(BankIcon),
  "battery-charging": withDuotone(BatteryChargingIcon),
  bell: withDuotone(BellIcon),
  bicycle: withDuotone(BicycleIcon),
  binoculars: withDuotone(BinocularsIcon),
  bookmark: withDuotone(BookmarkIcon),
  book: withDuotone(BookIcon),
  books: withDuotone(BooksIcon),
  briefcase: withDuotone(BriefcaseIcon),
  browser: withDuotone(BrowserIcon),
  buildings: withDuotone(BuildingsIcon),
  calendar: withDuotone(CalendarIcon),
  camera: withDuotone(CameraIcon),
  "caret-down": withDuotone(CaretDownIcon),
  "caret-left": withDuotone(CaretLeftIcon),
  "caret-right": withDuotone(CaretRightIcon),
  "caret-up": withDuotone(CaretUpIcon),
  car: withDuotone(CarIcon),
  certificate: withDuotone(CertificateIcon),
  "chart-bar": withDuotone(ChartBarIcon),
  "chart-line-up": withDuotone(ChartLineUpIcon),
  "chart-pie-slice": withDuotone(ChartPieSliceIcon),
  "chat-circle": withDuotone(ChatCircleIcon),
  "chat-circle-text": withDuotone(ChatCircleTextIcon),
  "clipboard-text": withDuotone(ClipboardTextIcon),
  clock: withDuotone(ClockIcon),
  cloud: withDuotone(CloudIcon),
  "cloud-arrow-down": withDuotone(CloudArrowDownIcon),
  "cloud-arrow-up": withDuotone(CloudArrowUpIcon),
  compass: withDuotone(CompassIcon),
  "credit-card": withDuotone(CreditCardIcon),
  crown: withDuotone(CrownIcon),
  "currency-circle-dollar": withDuotone(CurrencyCircleDollarIcon),
  desktop: withDuotone(DesktopIcon),
  "device-mobile": withDuotone(DeviceMobileIcon),
  "dice-five": withDuotone(DiceFiveIcon),
  "door-open": withDuotone(DoorOpenIcon),
  "download-simple": withDuotone(DownloadSimpleIcon),
  envelope: withDuotone(EnvelopeIcon),
  eye: withDuotone(EyeIcon),
  factory: withDuotone(FactoryIcon),
  file: withDuotone(FileIcon),
  fire: withDuotone(FireIcon),
  flag: withDuotone(FlagIcon),
  flower: withDuotone(FlowerIcon),
  folder: withDuotone(FolderIcon),
  "game-controller": withDuotone(GameControllerIcon),
  gear: withDuotone(GearIcon),
  gift: withDuotone(GiftIcon),
  "git-branch": withDuotone(GitBranchIcon),
  globe: withDuotone(GlobeIcon),
  "globe-hemisphere-west": withDuotone(GlobeHemisphereWestIcon),
  "hand-coins": withDuotone(HandCoinsIcon),
  "hand-palm": withDuotone(HandPalmIcon),
  "hand-waving": withDuotone(HandWavingIcon),
  "hard-drives": withDuotone(HardDrivesIcon),
  headphones: withDuotone(HeadphonesIcon),
  heart: withDuotone(HeartIcon),
  house: withDuotone(HouseIcon),
  "identification-card": withDuotone(IdentificationCardIcon),
  image: withDuotone(ImageIcon),
  key: withDuotone(KeyIcon),
  lamp: withDuotone(LampIcon),
  laptop: withDuotone(LaptopIcon),
  lifebuoy: withDuotone(LifebuoyIcon),
  lightning: withDuotone(LightningIcon),
  "list-bullets": withDuotone(ListBulletsIcon),
  lock: withDuotone(LockIcon),
  "magnifying-glass": withDuotone(MagnifyingGlassIcon),
  "map-pin": withDuotone(MapPinIcon),
  "map-trifold": withDuotone(MapTrifoldIcon),
  medal: withDuotone(MedalIcon),
  megaphone: withDuotone(MegaphoneIcon),
  microphone: withDuotone(MicrophoneIcon),
  moon: withDuotone(MoonIcon),
  "music-notes": withDuotone(MusicNotesIcon),
  newspaper: withDuotone(NewspaperIcon),
  package: withDuotone(PackageIcon),
  palette: withDuotone(PaletteIcon),
  paperclip: withDuotone(PaperclipIcon),
  "paper-plane-tilt": withDuotone(PaperPlaneTiltIcon),
  pause: withDuotone(PauseIcon),
  "pencil-simple": withDuotone(PencilSimpleIcon),
  phone: withDuotone(PhoneIcon),
  play: withDuotone(PlayIcon),
  receipt: withDuotone(ReceiptIcon),
  repeat: withDuotone(RepeatIcon),
  "rocket-launch": withDuotone(RocketLaunchIcon),
  rss: withDuotone(RssIcon),
  scales: withDuotone(ScalesIcon),
  "shield-check": withDuotone(ShieldCheckIcon),
  "shopping-bag": withDuotone(ShoppingBagIcon),
  "shopping-cart": withDuotone(ShoppingCartIcon),
  shuffle: withDuotone(ShuffleIcon),
  smiley: withDuotone(SmileyIcon),
  sparkle: withDuotone(SparkleIcon),
  star: withDuotone(StarIcon),
  suitcase: withDuotone(SuitcaseIcon),
  sun: withDuotone(SunIcon),
  tag: withDuotone(TagIcon),
  television: withDuotone(TelevisionIcon),
  "thumbs-down": withDuotone(ThumbsDownIcon),
  "thumbs-up": withDuotone(ThumbsUpIcon),
  ticket: withDuotone(TicketIcon),
  train: withDuotone(TrainIcon),
  tray: withDuotone(TrayIcon),
  "user-circle": withDuotone(UserCircleIcon),
  user: withDuotone(UserIcon),
  "users-three": withDuotone(UsersThreeIcon),
  "video-camera": withDuotone(VideoCameraIcon),
  waveform: withDuotone(WaveformIcon),
} as const satisfies Record<string, ButtonIconComponent>;

export type ButtonIconName = keyof typeof BUTTON_ICON_COMPONENTS;

export interface ButtonIconEntry {
  name: ButtonIconName;
  label: string;
  keywords?: readonly string[];
}

export const BUTTON_ICON_LIST: readonly ButtonIconEntry[] = [
  { name: "address-book", label: "Address Book", keywords: ["contacts", "directory"] },
  { name: "airplane", label: "Airplane", keywords: ["flight", "travel"] },
  { name: "alarm", label: "Alarm", keywords: ["clock", "alert"] },
  { name: "archive-box", label: "Archive Box", keywords: ["archive", "storage"] },
  { name: "armchair", label: "Armchair", keywords: ["furniture", "comfort"] },
  { name: "arrow-bend-down-left", label: "Arrow Bend Down Left", keywords: ["turn", "corner"] },
  { name: "arrow-bend-down-right", label: "Arrow Bend Down Right", keywords: ["turn", "corner"] },
  { name: "arrow-bend-up-left", label: "Arrow Bend Up Left", keywords: ["turn", "corner"] },
  { name: "arrow-bend-up-right", label: "Arrow Bend Up Right", keywords: ["turn", "corner"] },
  { name: "arrow-circle-down", label: "Arrow Circle Down", keywords: ["down", "circle"] },
  { name: "arrow-circle-left", label: "Arrow Circle Left", keywords: ["left", "circle"] },
  { name: "arrow-circle-right", label: "Arrow Circle Right", keywords: ["right", "circle"] },
  { name: "arrow-circle-up", label: "Arrow Circle Up", keywords: ["up", "circle"] },
  { name: "arrow-clockwise", label: "Arrow Clockwise", keywords: ["refresh", "reload"] },
  {
    name: "arrow-counter-clockwise",
    label: "Arrow Counter Clockwise",
    keywords: ["undo", "back"],
  },
  { name: "arrow-down", label: "Arrow Down", keywords: ["down"] },
  { name: "arrow-elbow-down-left", label: "Arrow Elbow Down Left", keywords: ["turn", "corner"] },
  {
    name: "arrow-elbow-down-right",
    label: "Arrow Elbow Down Right",
    keywords: ["turn", "corner"],
  },
  { name: "arrow-elbow-left", label: "Arrow Elbow Left", keywords: ["return", "left"] },
  { name: "arrow-elbow-right", label: "Arrow Elbow Right", keywords: ["return", "right"] },
  { name: "arrow-elbow-up-left", label: "Arrow Elbow Up Left", keywords: ["turn", "corner"] },
  { name: "arrow-elbow-up-right", label: "Arrow Elbow Up Right", keywords: ["turn", "corner"] },
  { name: "arrow-left", label: "Arrow Left", keywords: ["left"] },
  { name: "arrow-right", label: "Arrow Right", keywords: ["right"] },
  { name: "arrow-square-out", label: "Arrow Square Out", keywords: ["external", "open"] },
  { name: "arrow-up", label: "Arrow Up", keywords: ["up"] },
  { name: "bag", label: "Bag", keywords: ["shopping", "store"] },
  { name: "balloon", label: "Balloon", keywords: ["party", "celebration"] },
  { name: "bank", label: "Bank", keywords: ["finance", "building"] },
  { name: "battery-charging", label: "Battery Charging", keywords: ["power", "energy"] },
  { name: "bell", label: "Bell", keywords: ["notification", "alert"] },
  { name: "bicycle", label: "Bicycle", keywords: ["bike", "mobility"] },
  { name: "binoculars", label: "Binoculars", keywords: ["search", "discover"] },
  { name: "bookmark", label: "Bookmark", keywords: ["save"] },
  { name: "book", label: "Book", keywords: ["read"] },
  { name: "books", label: "Books", keywords: ["library", "read"] },
  { name: "briefcase", label: "Briefcase", keywords: ["business", "work"] },
  { name: "browser", label: "Browser", keywords: ["web", "window"] },
  { name: "buildings", label: "Buildings", keywords: ["city", "company"] },
  { name: "calendar", label: "Calendar", keywords: ["date", "schedule"] },
  { name: "camera", label: "Camera", keywords: ["photo"] },
  { name: "caret-down", label: "Caret Down", keywords: ["chevron", "down"] },
  { name: "caret-left", label: "Caret Left", keywords: ["chevron", "left"] },
  { name: "caret-right", label: "Caret Right", keywords: ["chevron", "right"] },
  { name: "caret-up", label: "Caret Up", keywords: ["chevron", "up"] },
  { name: "car", label: "Car", keywords: ["vehicle", "travel"] },
  { name: "certificate", label: "Certificate", keywords: ["award", "badge"] },
  { name: "chart-bar", label: "Chart Bar", keywords: ["analytics", "stats"] },
  { name: "chart-line-up", label: "Chart Line Up", keywords: ["analytics", "growth"] },
  { name: "chart-pie-slice", label: "Chart Pie Slice", keywords: ["analytics", "stats"] },
  { name: "chat-circle", label: "Chat Circle", keywords: ["message", "bubble"] },
  { name: "chat-circle-text", label: "Chat Circle Text", keywords: ["message", "text"] },
  { name: "clipboard-text", label: "Clipboard Text", keywords: ["notes", "copy"] },
  { name: "clock", label: "Clock", keywords: ["time"] },
  { name: "cloud", label: "Cloud", keywords: ["weather", "online"] },
  { name: "cloud-arrow-down", label: "Cloud Arrow Down", keywords: ["download", "sync"] },
  { name: "cloud-arrow-up", label: "Cloud Arrow Up", keywords: ["upload", "sync"] },
  { name: "compass", label: "Compass", keywords: ["navigation", "direction"] },
  { name: "credit-card", label: "Credit Card", keywords: ["payment"] },
  { name: "crown", label: "Crown", keywords: ["premium", "royal"] },
  {
    name: "currency-circle-dollar",
    label: "Currency Circle Dollar",
    keywords: ["money", "price"],
  },
  { name: "desktop", label: "Desktop", keywords: ["computer", "screen"] },
  { name: "device-mobile", label: "Device Mobile", keywords: ["phone", "mobile"] },
  { name: "dice-five", label: "Dice", keywords: ["game", "random"] },
  { name: "door-open", label: "Door Open", keywords: ["enter", "exit"] },
  { name: "download-simple", label: "Download Simple", keywords: ["download"] },
  { name: "envelope", label: "Envelope", keywords: ["mail", "email"] },
  { name: "eye", label: "Eye", keywords: ["view", "show"] },
  { name: "factory", label: "Factory", keywords: ["industry", "production"] },
  { name: "file", label: "File", keywords: ["document"] },
  { name: "fire", label: "Fire", keywords: ["hot", "flame"] },
  { name: "flag", label: "Flag", keywords: ["marker", "goal"] },
  { name: "flower", label: "Flower", keywords: ["nature", "garden"] },
  { name: "folder", label: "Folder", keywords: ["directory"] },
  { name: "game-controller", label: "Game Controller", keywords: ["gaming"] },
  { name: "gear", label: "Gear", keywords: ["settings"] },
  { name: "gift", label: "Gift", keywords: ["present"] },
  { name: "git-branch", label: "Git Branch", keywords: ["branch", "code"] },
  { name: "globe", label: "Globe", keywords: ["world", "website"] },
  {
    name: "globe-hemisphere-west",
    label: "Globe Hemisphere West",
    keywords: ["world", "global"],
  },
  { name: "hand-coins", label: "Hand Coins", keywords: ["money", "donation"] },
  { name: "hand-palm", label: "Hand Palm", keywords: ["stop", "halt"] },
  { name: "hand-waving", label: "Hand Waving", keywords: ["hello"] },
  { name: "hard-drives", label: "Hard Drives", keywords: ["storage", "server"] },
  { name: "headphones", label: "Headphones", keywords: ["audio", "music"] },
  { name: "heart", label: "Heart", keywords: ["favorite", "like"] },
  { name: "house", label: "House", keywords: ["home"] },
  {
    name: "identification-card",
    label: "Identification Card",
    keywords: ["id", "profile"],
  },
  { name: "image", label: "Image", keywords: ["picture", "photo"] },
  { name: "key", label: "Key", keywords: ["access"] },
  { name: "lamp", label: "Lamp", keywords: ["idea", "light"] },
  { name: "laptop", label: "Laptop", keywords: ["computer", "work"] },
  { name: "lifebuoy", label: "Lifebuoy", keywords: ["help", "support"] },
  { name: "lightning", label: "Lightning", keywords: ["fast", "energy"] },
  { name: "list-bullets", label: "List Bullets", keywords: ["menu", "list"] },
  { name: "lock", label: "Lock", keywords: ["secure", "privacy"] },
  { name: "magnifying-glass", label: "Magnifying Glass", keywords: ["search"] },
  { name: "map-pin", label: "Map Pin", keywords: ["location", "pin"] },
  { name: "map-trifold", label: "Map Trifold", keywords: ["map", "location"] },
  { name: "medal", label: "Medal", keywords: ["award", "winner"] },
  { name: "megaphone", label: "Megaphone", keywords: ["announcement", "marketing"] },
  { name: "microphone", label: "Microphone", keywords: ["audio", "voice"] },
  { name: "moon", label: "Moon", keywords: ["night", "theme"] },
  { name: "music-notes", label: "Music Notes", keywords: ["music", "audio"] },
  { name: "newspaper", label: "Newspaper", keywords: ["news", "article"] },
  { name: "package", label: "Package", keywords: ["box", "delivery"] },
  { name: "palette", label: "Palette", keywords: ["design", "color"] },
  { name: "paper-plane-tilt", label: "Paper Plane", keywords: ["send"] },
  { name: "paperclip", label: "Paperclip", keywords: ["attachment"] },
  { name: "pause", label: "Pause", keywords: ["stop"] },
  { name: "pencil-simple", label: "Pencil Simple", keywords: ["edit", "write"] },
  { name: "phone", label: "Phone", keywords: ["call", "telephone"] },
  { name: "play", label: "Play", keywords: ["start"] },
  { name: "receipt", label: "Receipt", keywords: ["invoice", "bill"] },
  { name: "repeat", label: "Repeat", keywords: ["loop"] },
  { name: "rocket-launch", label: "Rocket Launch", keywords: ["launch", "fast"] },
  { name: "rss", label: "RSS", keywords: ["feed", "news"] },
  { name: "scales", label: "Scales", keywords: ["balance", "justice"] },
  { name: "shield-check", label: "Shield Check", keywords: ["security", "safe"] },
  { name: "shopping-bag", label: "Shopping Bag", keywords: ["bag", "shop"] },
  { name: "shopping-cart", label: "Shopping Cart", keywords: ["cart", "shop"] },
  { name: "shuffle", label: "Shuffle", keywords: ["random"] },
  { name: "smiley", label: "Smiley", keywords: ["face", "happy"] },
  { name: "sparkle", label: "Sparkle", keywords: ["magic", "highlight"] },
  { name: "star", label: "Star", keywords: ["favorite", "featured"] },
  { name: "suitcase", label: "Suitcase", keywords: ["travel", "luggage"] },
  { name: "sun", label: "Sun", keywords: ["day", "weather"] },
  { name: "tag", label: "Tag", keywords: ["label", "price"] },
  { name: "television", label: "Television", keywords: ["tv", "screen"] },
  { name: "thumbs-down", label: "Thumbs Down", keywords: ["dislike"] },
  { name: "thumbs-up", label: "Thumbs Up", keywords: ["like"] },
  { name: "ticket", label: "Ticket", keywords: ["event", "entry"] },
  { name: "train", label: "Train", keywords: ["travel", "transport"] },
  { name: "tray", label: "Tray", keywords: ["inbox", "download"] },
  { name: "user-circle", label: "User Circle", keywords: ["profile", "account"] },
  { name: "user", label: "User", keywords: ["person"] },
  { name: "users-three", label: "Users", keywords: ["group", "people"] },
  { name: "video-camera", label: "Video Camera", keywords: ["video"] },
  { name: "waveform", label: "Waveform", keywords: ["audio", "sound"] },
];

export function getButtonIconComponent(
  name: string | null | undefined,
): ButtonIconComponent | null {
  if (!name || !(name in BUTTON_ICON_COMPONENTS)) {
    return null;
  }

  return BUTTON_ICON_COMPONENTS[name as ButtonIconName];
}
